pascal_voc_generator:
  train:
    image_shape:
      - 500
      - 500
      - 3
    image_resample: True
    pixelwise_center: True
    pixel_mean:
      - 104.00699
      - 116.66877
      - 122.67892
  test:
    image_shape:
      - 500
      - 500
      - 3
    image_resample: True
    pixelwise_center: True
    pixel_mean:
      - 104.00699
      - 116.66877
      - 122.67892
  flow_from_imageset:
    class_mode: 'categorical'
    classes: 21
    batch_size: 1
    shuffle: True
image_set_loader:
  train:
    image_set: ./data/voc/ImageSets/Segmentation/train.txt
    image_dir: ./data/voc/JPEGImages/
    label_dir: ./data/voc/SegmentationClass
    target_size:
      - 500
      - 500
    image_format: 'jpg'
    color_mode: 'rgb'
    label_format: 'png'
  val:
    image_set: ./data/voc/ImageSets/Segmentation/val.txt
    image_dir: ./data/voc/JPEGImages/
    label_dir: ./data/voc/SegmentationClass
    target_size:
      - 500
      - 500
    image_format: 'jpg'
    color_mode: 'rgb'
    label_format: 'png'
